### ISSUE TITLE
pre-trained model update

### ISSUE THREAD

**Issue by lynnjeoun** [HUANGLIZI/LViT#10]
Hi, I am very impressed by your work!

I would like to know when your pre-trained model will be updated.

Thank you

**Comment by HUANGLIZI** [comment]
Could you email me? And I will keep you posted on the updated info. Thanks

**Comment by lynnjeoun** [comment]
Hi, sorry for late reply.

Yes, please. Thank you.

Happy new year,
Bosoung, Jeoun



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23-01-03,
09:48:04 a.m.

2022년 12월 28일 (수) 오전 2:37, Zihan Li ***@***.***>님이 작성:

**Comment by SusmitaSenGhosh** [comment]
Hi, congratulations on such a good work. 
Could please share the pre-trained models for MonuSeg dataset.
