### ISSUE TITLE
关于您实验部分的不理解，能够方便加vx 或者您的邮箱

### ISSUE THREAD

**Issue by 754467737** [HUANGLIZI/LViT#12]

**Comment by HUANGLIZI** [comment]
Please email to me if you have any question.

**Comment by 754467737** [comment]
您有没有运行过UCTransnet来测试GLAS数据集？结果是怎么样的？我测试的结果，目前Unet在GLAS上的五折交叉验证法，精度在89+-0.5，而作者的UCTransnet才87.21+-1.3。很不解这种情况，太差了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HUANGLIZI/LViT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 上午9:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HUANGLIZI/LViT] 关于您实验部分的不理解，能够方便加vx 或者您的邮箱 (Issue #12)





 
Please email to me if you have any question.
