### ISSUE TITLE
bert_embedding 只能兼容numpy1.14.6, 此版本与其它包不兼容，先安装bert_embedding 再装numpy也不行

### ISSUE THREAD

**Issue by long-island-ice-tea** [HUANGLIZI/LViT#13]
bert_embedding 只能兼容numpy1.14.6, 此版本与其它包不兼容，先安装bert_embedding 再装numpy也不行

**Comment by HUANGLIZI** [comment]
It is recommended to recreate a virtual conda environment and ensure that the installed library version is consistent with that in requirement.txt.
