### ISSUE TITLE
About the text annotation

### ISSUE THREAD

**Issue by Tristtels** [HUANGLIZI/LViT#14]
Is the text annotation made by yourself? If I want to train my own dataset, do I need to make it？

**Comment by HUANGLIZI** [comment]
The text annotation is made by the radiologist. And if you want to train your own dataset, maybe you can generate the text annotation through the mask.

**Comment by xskdjs444** [comment]
你好，大佬，感谢您很有启发性的工作。我想问一下如果我想用其他的2D数据集，比如GLAS，BUSI，ISIC这些，如何用mask来生成text标注，可以提供一下对应的生成代码或者思路吗？期待您的回复！
