### ISSUE TITLE
Dependencies installing

### ISSUE THREAD

**Issue by Aki-07** [HUANGLIZI/LViT#15]
Your work is very remarkable but while trying to run the code on my local machine 
 I am unable to run it
I have created a virtual conda environment and while trying to run conda install --file requirements.txt it shows many packages are not available in the current channels.So how should I run the code ?? while normal pip installing for bert-embedding It shows a legacy error .So if you could help me out

**Comment by HUANGLIZI** [comment]
If you have this situation, the best solution is to run the train.py, check the missing libraries, and install the corresponding package version.
