### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by scm-later** [HUANGLIZI/LViT#2]
AttributeError: 'LayerNorm' object has no attribute 'affine'
![1](https://user-images.githubusercontent.com/89558994/177024781-9bc531d4-35df-4247-ae4a-8b70c4643e09.PNG)
![2](https://user-images.githubusercontent.com/89558994/177024784-49701a03-1947-401f-a643-3485f4807ba7.PNG)

**Comment by HUANGLIZI** [comment]
Please provide details of the error message

**Comment by HUANGLIZI** [comment]
A high probability is caused by different versions.

**Comment by scm-later** [comment]
> 
Okay, thank you very much
