### ISSUE TITLE
Question about MosMedData+

### ISSUE THREAD

**Issue by tinalmas** [HUANGLIZI/LViT#20]
Hi,
The link you provided (http://medicalsegmentation.com/covid19) contains 100 axial CT images+9 volumes+20 volumes, but MosMedData contains 50 annotated volumes. I did not figure out why a smaller dataset (MosMedData+) includes a larger dataset (MosMedData). Can you provide any reference that describes MosMedData+ dataset and claims that it includes MosMedData?

Thanks.

**Comment by HUANGLIZI** [comment]
Hi, MosMedData+ contains some data from the MosMedData, so we call it MosMedData+.

**Comment by tinalmas** [comment]
> Hi, MosMedData+ contains some data from the MosMedData, so we call it MosMedData+.

Hi, from my understanding, there is no overlap between MosMedData and MosMedData+. Could you please elaborate which parts of MosMedData+ is from MosMedData? Thanks!

**Comment by ShashankHuang** [comment]
> Hi, The link you provided (http://medicalsegmentation.com/covid19) contains 100 axial CT images+9 volumes+20 volumes, but MosMedData contains 50 annotated volumes. I did not figure out why a smaller dataset (MosMedData+) includes a larger dataset (MosMedData). Can you provide any reference that describes MosMedData+ dataset and claims that it includes MosMedData?
> 
> Thanks.



Hello! I am in the same trouble. Have you figured out this problem?
