### ISSUE TITLE
How to get pre-trained models for MonuSeg dataset

### ISSUE THREAD

**Issue by SusmitaSenGhosh** [HUANGLIZI/LViT#21]
Hi, congratulations on such a good work.
Could please share the pre-trained models for MonuSeg dataset.

**Comment by HUANGLIZI** [comment]
Thanks for your attention on our work. Sorry for the pre-trained models for MonuSeg dataset is unavailable now. If you have any question about the training, you can drop me an email. Hope it can help you.
