### ISSUE TITLE
依赖安装问题

### ISSUE THREAD

**Issue by yjh-god** [HUANGLIZI/LViT#22]
你好！毋庸置疑您的论文写的非常出色，本人也相当想复刻你的代码，但是我在安装依赖时遇到了问题，按你所言python版本要为3.7，我在服务器上面的版本是3.8，我觉得这是兼容的，然后在直接安装,text时，报错numpy版本冲突，我尝试了先装bert-embedding再装.text，也试过先装bert-embedding，再装numpy==1.17.5，最后装.text，最后尝试了创建一个新的虚拟环境再来装这些依赖，但也同样报错，希望您能教教我，该怎么一步一步正确安装依赖，谢谢您！

**Comment by HUANGLIZI** [comment]
You should strictly adhere to the dependent library version in the file requirement.txt. In addition, we do not know what is the .text? The .text is not required in our task. Or you can simply run the train.py, and see what is missing, then you can install the corresponding version of dependency library.

**Comment by yjh-god** [comment]
很抱歉，我上述说的.text就是.txt。我尝试了你的方法，简单运行了train.py，但依然在numpy版本冲突这卡住了，因此我很困扰，希望你能再帮我指出一个方法，来正确安装依赖，麻烦了！
