### ISSUE TITLE
request to release the EPI code part 

### ISSUE THREAD

**Issue by webzerg** [HUANGLIZI/LViT#23]
Can you release the EPI code part now? This is a core part of the paper, we appreciate you can release it so we can reproduce the result. Thanks.

**Comment by HUANGLIZI** [comment]
You can utilize the Exponential Pseudo-label Iteration mechanism (EPI) to generate the Pseudo-label. And you need to train a prototype model using the labeled data to generate the Pseudo-label for the unlabeled data. Then you can use the pseudo-label and the GT to train using all data. For the LV Loss, you can refer to the Fig. 3 to design the Contrastive label.
