### ISSUE TITLE
关于依赖中numpy版本冲突问题

### ISSUE THREAD

**Issue by yjh-god** [HUANGLIZI/LViT#24]
您好！很抱歉再次打扰到您，我在复现您的代码的过程中总是被numpy版本冲突这个问题卡住，我尝试了先装bert,再装numpy还是不行，然后尝试了您之前所说的简单运行.train，我在运行过程中还是由于numpy版本冲突而停滞不前，我也尝试过创建一个新的虚拟环境，但仍然是在这个报错卡住，所以请求您能给你我一个具体的解决办法，谢谢您！

**Comment by HUANGLIZI** [comment]
Please provide detailed error information.

**Comment by yjh-god** [comment]
很抱歉现在才回复您，我之前遇到报错的时候并没有去保存信息，因此我重新走了一遍，现在我把报错的信息给您，希望您能给我提供方法，谢谢！
![9c4fdc0542114ebb9d469b840b7b81b](https://github.com/HUANGLIZI/LViT/assets/129289775/5d882465-0848-43e6-a31d-b6ebc2a8c1e2)

**Comment by HUANGLIZI** [comment]
You should install every dependency one by one and not use pip install -r requirement.txt
