### ISSUE TITLE
3D模型

### ISSUE THREAD

**Issue by yjh-god** [HUANGLIZI/LViT#25]
您好！很抱歉再次打扰到您，我想请问您已经提出3D模型了吗？我目前想做个3D的多模数据集，在您2D模型上面实现不了，另外我想请求您能告诉我一些公开的3D多模数据集，谢谢！

**Comment by HUANGLIZI** [comment]
Thanks for your feedback, we are developing the LViT-3D model, and the public 3D multimodal dataset may not includes the language information currently.

**Comment by yjh-god** [comment]
谢谢您的回答，我将关闭这个问题。
