### ISSUE TITLE
How to match the images of the MosMedData+ dataset with its text annotations?

### ISSUE THREAD

**Issue by Labhahaha** [HUANGLIZI/LViT#29]
Hello. Thank you very much for sharing the text annotation of MosMedData+Dataset. But I am confused about how to match the images of the dataset with text annotations. 
Specifically, there are several types of image naming in your text annotation: 'bjorke'_ X ',' Jun_ Coronacases_ CaseX ',' Jun_ Radiopaedia_ X ',' Morozov_ Study_ X '.
From my guess, 'bjorke'_ X ' may corresponds to' COVID-19 CT segmentation dataset ', while' Jun '_ Coronacases_ CaseX 'and' Jun_ Radiopaedia_ X ' may corresponds to' COVID-19-CT-Seg_ 20 cases'. then which image data does 'morozov study ' correspond to?
I'm sorry for being confused about this. Can you provide detailed instructions on how to match them?

**Comment by HUANGLIZI** [comment]
You can download the dataset from the link https://www.kaggle.com/datasets/maedemaftouni/covid19-ct-scan-lesion-segmentation-dataset
