### ISSUE TITLE
Training details on QaTa-COV19 Dataset

### ISSUE THREAD

**Issue by Lewis-lv0** [HUANGLIZI/LViT#3]
Hi there,

I am trying to reproduce your results on QaTa-COV19 Dataset. But I am wondering how you do the Train-Val split on QaTa-COV19 Dataset. Could you release more details about that? Thanks.

Also looking forward to the text annotations on this dataset.

**Comment by HUANGLIZI** [comment]
I am sorry that the text annotations on the QaTa-COV19 dataset are unavailable because the paper is under-reviewed. Please get in touch with me by E-mail, and I can send you the Train-Val split on QaTa-COV19 Dataset. Thanks a lot.

**Comment by Lewis-lv0** [comment]
OK. Could I have your email? Thanks.

**Comment by HUANGLIZI** [comment]
You can send it to the email listed on the paper.

**Comment by Lewis-lv0** [comment]
OK. I sent you the email just now and I will close this issue. Thanks a lot.
