### ISSUE TITLE
pre-train checkpoint and comparing without text

### ISSUE THREAD

**Issue by uurcelikk** [HUANGLIZI/LViT#30]
I congratulate you for your work. 
I would like to ask about your work, can I access the pth.tar checkpoint to work pre-train with the MonuSeg dataset? And how can I run this model without  the text data? Thanks

**Comment by HUANGLIZI** [comment]
You can just use the image feature to replace the text feature when training without the text data. And unfortunately, the checkpoint file may not be available now.
