### ISSUE TITLE
Questions about datasets preparation

### ISSUE THREAD

**Issue by Studentpengyu** [HUANGLIZI/LViT#31]
Dear Zihan,

Thank you for your amazing work. I am currently attempting to replicate your study for further research. However, I've encountered an issue with the dataset formats for QaTa-COV19 and MosMedData+. 

To address these concerns, I have sent a detailed email outlining the specific issues encountered with the dataset formats.

Your feedback would be greatly appreciated, and I eagerly await your response. Thank you very much for your time and consideration.

Best regards,
Pengyu Zhao

**Comment by HUANGLIZI** [comment]
Unfortunately, I didn't receive the email from you. Could you send it again to my email address: zhanli@uw.edu?

**Comment by Studentpengyu** [comment]
It appears there was an issue that prevented my previous email from reaching you, potentially due to Tianjin University's email server being flagged. To address this, I have resent the email using my 163 email account.
