### ISSUE TITLE
Inquiry About PixLevelModule Usage in LViT Network Structure

### ISSUE THREAD

**Issue by Studentpengyu** [HUANGLIZI/LViT#35]
Dear Zihan,

I hope this message finds you well. As I delve deeper into the LViT model, I have encountered a specific aspect of the network structure that I am eager to understand better with your guidance.

In my thorough examination of the LViT's network architecture, I observed that the PixLevelModule, as defined in the code, appears not to be used in the forward pass. To better illustrate my point, I am referencing the following sections of the code from your GitHub repository:
![image](https://github.com/HUANGLIZI/LViT/assets/57900441/647955c4-ce2f-4170-bc1b-3e1d51858487)
![image](https://github.com/HUANGLIZI/LViT/assets/57900441/8c71e74a-bc26-4967-8733-6458c4576862)
![image](https://github.com/HUANGLIZI/LViT/assets/57900441/b784c181-6a3d-4106-896f-18aa16bacee6)

This observation has led to some confusion about its role in the overall network structure as described in your paper. Could you kindly provide clarification on this and, if possible, share the correct code that reflects the implementation used in the paper?

Your insights are invaluable to my understanding and proper implementation of the LViT model. I greatly appreciate your time and the support you've provided thus far.

Thank you once again for your assistance.

Best regards,
Pengyu

**Comment by HUANGLIZI** [comment]
There is some redundancy in the code, but you can use it freely. And the code has been the proper implementation of the LViT model.
