### ISSUE TITLE
error: Bert embedding library.

### ISSUE THREAD

**Issue by uurcelikk** [HUANGLIZI/LViT#36]
Hello, thank you for your all works.

I want to ask about that library _from bert_embedding import BertEmbedding_ . this library returns an error. not loading the library. returns this error subprocess-exited-with-error.

How can i fix that error?

**Comment by HUANGLIZI** [comment]
Hi,
You can refer to the link https://pypi.org/project/bert-embedding/ to install bert-embedding, then import it.
