### ISSUE TITLE
Pre-training

### ISSUE THREAD

**Issue by acmername** [HUANGLIZI/LViT#42]
Do the experimental results obtained in Table 2 of the paper use a pre-trained model? Using pre-training works well on the COVID-19 dataset, but the other one is not good.If not used, the opposite experiment is obtained.

**Comment by acmername** [comment]
And my GPU is a 2-card TESLA V100 32G.Looking forward to your recovery.

**Comment by HUANGLIZI** [comment]
The performance may have something with the GPU used and the hyperparameters may be different. So you can choose what is best for your setup.
