### ISSUE TITLE
Some question about text feature dimension

### ISSUE THREAD

**Issue by SCUT-CCNL** [HUANGLIZI/LViT#44]
![image](https://github.com/HUANGLIZI/LViT/assets/33176838/335e742f-77cd-4bd0-b0a3-6dd5ff1623c8)
![image](https://github.com/HUANGLIZI/LViT/assets/33176838/889e101e-7010-4f43-9e3f-f4b07a812e5a)
为什么输入的维度为[2*10*768]，batch为2，10是什么意思呢？768是bert编码的特征数？

**Comment by HUANGLIZI** [comment]
10 is the cut-off size. And you should recheck bert model if you want to explore more options.
