### ISSUE TITLE
Inquiry About Generating CAM Images with LViT

### ISSUE THREAD

**Issue by Studentpengyu** [HUANGLIZI/LViT#45]
Dear Zihan,

I hope this message finds you well.

I have been following your work with great interest. Currently, I am attempting to replicate the interpretability Study in your paper However, I have encountered some challenges.

I am using the package 'pytorch_grad_cam' with the following code snippet:
![image](https://github.com/HUANGLIZI/LViT/assets/57900441/acb37c12-fd41-40bd-b2d4-1d47539d3857)
![image](https://github.com/HUANGLIZI/LViT/assets/57900441/9d1b10c2-41d7-456c-9815-4fefe2a337cd)

'cam' requires the model's input to be a single tensor, whereas the LViT model requires two tensors (image, text) as input. I would like to ask how you generated the CAM figures in your work. Could you kindly provide some guidance or share the relevant code?

Thank you very much for your time and assistance.

Best regards,
Pengyu Zhao

**Comment by HUANGLIZI** [comment]
You should change the source code of GradCAM. And make it adaptable for two inputs.

**Comment by Studentpengyu** [comment]
Thank you for your response. I have obtained the expected results for the LViT model and cited it correctly. I appreciate all your help along the way.
