### ISSUE TITLE
Question about UNet

### ISSUE THREAD

**Issue by blz822** [HUANGLIZI/LViT#46]
Dear Zihan Li,

Thank you for your excellent work!

I have been following your work and have successfully used the setting 'model_type="LViT"' to run the code. However, I have encountered some challenges in replacing LVIT with U-Net for model training.

As discussed in Section 2.1 of your documentation:
![image](https://github.com/HUANGLIZI/LViT/assets/53861094/c32d5d0d-6cfe-42d3-983a-e6a91e756451)

Your guidance on these matters would be greatly appreciated, as it would greatly assist me in understanding and utilizing your work more effectively.

Thank you for your time and consideration. I am looking forward to your valuable insights.

Best regards,
Bao

**Comment by HUANGLIZI** [comment]
You can use the UNet we provided for the pre-training: https://github.com/HUANGLIZI/LViT/blob/main/nets/UNet.py
