### ISSUE TITLE
LVIT论文询问

### ISSUE THREAD

**Issue by HuashengPang** [HUANGLIZI/LViT#7]
李老师你好，我是重庆邮电大学的研究生，看到了你这篇LViT论文，写得很好，但是我有些不懂的地方，所以想询问你一下几个问题？就是这篇论文中数据集，验证集和训练集的划分标注。covid19对比标签是什么，文中不同结构形式的文本构成对比标签，这个是怎么构成的呢？还请您解答一下，谢谢老师！！

**Comment by HUANGLIZI** [comment]
The dataset partition can be downloaded from the link in the repo. And please email me for the contrastive label.

**Comment by HUANGLIZI** [comment]
The partition of the train set and val set of QaTa-COV19 dataset https://1drv.ms/u/s!AihndoV8PhTDgt82Do5kj33mUee33g?e=kzWl8y
