### ISSUE TITLE
python版本？

### ISSUE THREAD

**Issue by gaoxx37** [HUANGLIZI/LViT#8]
大佬好，我在复现论文的实验遇到了问题。我在win10平台下基于anaconda进行python环境配置。按照readme指引安装了numpy1.17.5。（numpy官网对1.17.5的python版本要求是3.5-3.8.）然后我在批量安装requirements.txt时出现了冲突，如下图所示
![image](https://user-images.githubusercontent.com/12195985/202884343-81c6be4b-56b1-4c9a-b824-72882539e098.png)
不同包对python版本的要求不兼容，请问大佬是如何处理这个问题的？

**Comment by HUANGLIZI** [comment]
Please install python==3.7.0. Thanks for your reminder.

**Comment by gaoxx37** [comment]
> Please install python==3.7.0. Thanks for your reminder.

But the compatible versions of cycler（ver0.10.0) are python2.6.* and 3.3.*,as shown in picture above.

**Comment by HUANGLIZI** [comment]
It is compatible in terms of my attempt.
