### ISSUE TITLE
Code for EPI

### ISSUE THREAD

**Issue by MIRONERAT** [HUANGLIZI/LViT#9]
Hello, your paper is interesting.
I have some questions about Exponential Pseudo-label Iteration mechanism, but I didn't find the code for this part. Did you push it on your repo?

**Comment by HUANGLIZI** [comment]
We will release the EPI code later. Thanks for your attention to our work.

**Comment by webzerg** [comment]
@HUANGLIZI Can you release the EPI code part now? This is a core part of the paper, we appreciate you can release it so we can reproduce the result. Thanks.
